### ISSUE TITLE
validator-ws uses old gbif-api?

### ISSUE THREAD

**Issue by timrobertson100** [gbif/pipelines#1068]
A user who has the `INVITED_TESTER` role is unable to submit validations.

Logs show as:

```

pipelines-validator-ws:

java.lang.IllegalArgumentException: No enum constant org.gbif.api.vocabulary.UserRole.INVITED_TESTER
	at java.lang.Enum.valueOf(Enum.java:238)
	at org.gbif.api.vocabulary.UserRole.valueOf(UserRole.java:21)
        ...

```

**Comment by marcos-lg** [comment]
seems to be fixed.
