### ISSUE TITLE
Inconsistent occurrence keys

### ISSUE THREAD

**Issue by asturcon** [gbif/pipelines#203]
Dataset d79555a1-e651-4c3a-b5ac-481b416446ad and attempt 113 failed with error message:

```
Final app status: FAILED, exitCode: 15, (reason: User class threw exception: org.apache.beam.sdk.Pipeline$PipelineExecutionException: java.lang.IllegalStateException: Found inconsistent occurrence keys in looking up unique identifiers:[d79555a1-e651-4c3a-b5ac-481b416446ad\|SMNS\|SMNS Palaeontology VI\|44663\|null]=[1132399784][d79555a1-e651-4c3a-b5ac-481b416446ad\|http://col.smns-bw.org/object/S10000408882005]=[1099529291]
        at org.apache.beam.runners.spark.SparkPipelineResult.beamExceptionFrom(SparkPipelineResult.java:65)
        at org.apache.beam.runners.spark.SparkPipelineResult.waitUntilFinish(SparkPipelineResult.java:98)
        at org.apache.beam.runners.spark.SparkPipelineResult.waitUntilFinish(SparkPipelineResult.java:86)
        at org.gbif.pipelines.ingest.pipelines.VerbatimToInterpretedPipeline.run(VerbatimToInterpretedPipeline.java:190)
        at org.gbif.pipelines.ingest.pipelines.VerbatimToInterpretedPipeline.main(VerbatimToInterpretedPipeline.java:82)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:688) Caused by: java.lang.IllegalStateException: Found inconsistent occurrence keys in looking up unique identifiers:[d79555a1-e651-4c3a-b5ac-481b416446ad\|SMNS\|SMNS Palaeontology VI\|44663\|null]=[1132399784][d79555a1-e651-4c3a-b5ac-481b416446ad\|http://col.smns-bw.org/object/S10000408882005]=[1099529291]
        at org.gbif.pipelines.keygen.HBaseLockingKeyService.failWithConflictingLookup(HBaseLockingKeyService.java:427)
        at org.gbif.pipelines.keygen.HBaseLockingKeyService.findKey(HBaseLockingKeyService.java:293)
        at org.gbif.pipelines.keygen.HBaseLockingKeyService.findKey(HBaseLockingKeyService.java:315)
        at org.gbif.pipelines.core.interpreters.core.BasicInterpreter.lambda$interpretGbifId$0(BasicInterpreter.java:85)
        at org.gbif.pipelines.core.Interpretation$Handler.lambda$via$0(Interpretation.java:97)
        at java.util.Optional.ifPresent(Optional.java:159)
        at org.gbif.pipelines.core.Interpretation$Handler.via(Interpretation.java:97)
        at org.gbif.pipelines.core.Interpretation$Condition.via(Interpretation.java:78)
        at org.gbif.pipelines.transforms.core.BasicTransform.processElement(BasicTransform.java:102)
```

Logs are in https://logs.gbif.org/app/kibana#/discover?_g=(refreshInterval:(display:On,pause:!f,value:0),time:(from:now-7d,mode:quick,to:now))&_a=(columns:!(_source),index:AWBa0XR-f8lu3pmE7ete,interval:auto,query:(query_string:(analyze_wildcard:!t,query:'datasetId:%22d79555a1-e651-4c3a-b5ac-481b416446ad%22%20AND%20attempt:%22113%22')),sort:!('@timestamp',desc))

**Comment by MattBlissett** [comment]
We get 1 occurrence failure in the existing processing, so I'm not immediately concerned that there's a general problem:

https://registry.gbif.org/dataset/d79555a1-e651-4c3a-b5ac-481b416446ad/process

**Comment by asturcon** [comment]
Another case:
`
User class threw exception: org.apache.beam.sdk.Pipeline$PipelineExecutionException: java.lang.IllegalStateException: Found inconsistent occurrence keys in looking up unique identifiers:[1e61b812-b2ec-43d0-bdbb-8534a761f74c|197d5f88-4a35-a354-24be-c0985ffb5833]=[1804388511][1e61b812-b2ec-43d0-bdbb-8534a761f74c|CMN|CANL|CANL 10002138|null]=[2243053193]
`
Logs: http://c5master2-vh.gbif.org:8088/cluster/app/application_1561148256758_51649

**Comment by asturcon** [comment]
Another case:
```
 Found inconsistent occurrence keys in looking up unique identifiers:[af1b4db0-c8ce-4a95-b700-8a6a02bed9d6|3A10107A-2E84-481D-8F8D-4ED61B6FB6E5]=[2284494154][af1b4db0-c8ce-4a95-b700-8a6a02bed9d6|USF|Herb|130865|null]=[2284494302]
```

Logs: http://c5master2-vh.gbif.org:8088/cluster/app/application_1561148256758_54527
