### ISSUE TITLE
Timeout at indexing

### ISSUE THREAD

**Issue by asturcon** [gbif/pipelines#208]
I've seen this error several times, but usually works when we rerun the pipeline:
```
961a5ce1-f843-4e75-86a6-51aa959fc12c 78 19/07/31 06:37:43 INFO EsIndexUtils: ES indexes default-static delete records by query {"query":{"match":{"datasetKey":"961a5ce1-f843-4e75-86a6-51aa959fc12c"}}}
961a5ce1-f843-4e75-86a6-51aa959fc12c 78 19/07/31 06:39:19 INFO EsIndex: 607514 records deleted from ES index default-static
961a5ce1-f843-4e75-86a6-51aa959fc12c 78 19/07/31 06:39:19 INFO InterpretedToEsIndexPipeline: Adding step 1: Options
961a5ce1-f843-4e75-86a6-51aa959fc12c 78 19/07/31 06:39:20 INFO InterpretedToEsIndexPipeline: Adding step 2: Creating transformations
961a5ce1-f843-4e75-86a6-51aa959fc12c 78 19/07/31 06:39:20 INFO InterpretedToEsIndexPipeline: Adding step 3: Creating beam pipeline
961a5ce1-f843-4e75-86a6-51aa959fc12c 78 19/07/31 06:39:21 INFO InterpretedToEsIndexPipeline: Adding step 3: Converting into a json object
961a5ce1-f843-4e75-86a6-51aa959fc12c 78 19/07/31 06:39:21 INFO InterpretedToEsIndexPipeline: Adding step 4: Elasticsearch indexing
961a5ce1-f843-4e75-86a6-51aa959fc12c 78 19/07/31 06:39:21 INFO InterpretedToEsIndexPipeline: Running the pipeline
  19/07/31 06:39:21 ERROR ApplicationMaster: Uncaught exception: 
java.util.concurrent.TimeoutException: Futures timed out after [100000 milliseconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:201)
	at org.apache.spark.deploy.yarn.ApplicationMaster.runDriver(ApplicationMaster.scala:455)
	at org.apache.spark.deploy.yarn.ApplicationMaster.org$apache$spark$deploy$yarn$ApplicationMaster$$runImpl(ApplicationMaster.scala:301)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anonfun$run$1.apply$mcV$sp(ApplicationMaster.scala:241)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anonfun$run$1.apply(ApplicationMaster.scala:241)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anonfun$run$1.apply(ApplicationMaster.scala:241)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$3.run(ApplicationMaster.scala:782)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1917)
	at org.apache.spark.deploy.yarn.ApplicationMaster.doAsUser(ApplicationMaster.scala:781)
	at org.apache.spark.deploy.yarn.ApplicationMaster.run(ApplicationMaster.scala:240)
	at org.apache.spark.deploy.yarn.ApplicationMaster$.main(ApplicationMaster.scala:806)
	at org.apache.spark.deploy.yarn.ApplicationMaster.main(ApplicationMaster.scala)
  19/07/31 06:39:21 INFO ApplicationMaster: Final app status: FAILED, exitCode: 13, (reason: Uncaught exception: java.util.concurrent.TimeoutException: Futures timed out after [100000 milliseconds])
  19/07/31 06:39:21 INFO ApplicationMaster: Deleting staging directory hdfs://ha-nn/user/hdfs/.sparkStaging/application_1561148256758_70657
  19/07/31 06:39:21 INFO ShutdownHookManager: Shutdown hook called
```

We should keep an eye on it to understand under what circumstances it happens.

Full logs: http://c5master2-vh.gbif.org:19888/jobhistory/logs//c5n2.gbif.org:8041/container_1561148256758_70657_01_000001/container_1561148256758_70657_01_000001/hdfs

**Comment by muttcg** [comment]
This dataset is less than 1m, it goes to "default" index, I presume cause we changed default indices workflow it will disappear. I will close by now and reopen in case of repetition.
