### ISSUE TITLE
"com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input" during indexing

### ISSUE THREAD

**Issue by muttcg** [gbif/pipelines#214]
```
f2e389da-39c3-4f21-8d72-b7d574d924a9 90 19/08/13 06:50:13 ERROR ApplicationMaster: User class threw exception: com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
 at [Source: UNKNOWN; line: 1, column: 1]
com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
 at [Source: UNKNOWN; line: 1, column: 1]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
	at com.fasterxml.jackson.databind.ObjectReader._initForReading(ObjectReader.java:381)
	at com.fasterxml.jackson.databind.ObjectReader._bindAsTree(ObjectReader.java:1539)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndCloseAsTree(ObjectReader.java:1528)
	at com.fasterxml.jackson.databind.ObjectReader.readTree(ObjectReader.java:1235)
	at org.gbif.pipelines.estools.service.JsonHandler.readTree(JsonHandler.java:86)
	at org.gbif.pipelines.estools.service.HttpRequestBuilder.withMappings(HttpRequestBuilder.java:95)
	at org.gbif.pipelines.estools.service.HttpRequestBuilder.createBodyFromIndexParams(HttpRequestBuilder.java:53)
	at org.gbif.pipelines.estools.service.EsService.createIndex(EsService.java:54)
	at org.gbif.pipelines.ingest.utils.EsIndexUtils.createIndexAndAliasForDefault(EsIndexUtils.java:54)
	at org.gbif.pipelines.ingest.pipelines.InterpretedToEsIndexExtendedPipeline.run(InterpretedToEsIndexExtendedPipeline.java:77)
	at org.gbif.pipelines.ingest.pipelines.InterpretedToEsIndexExtendedPipeline.run(InterpretedToEsIndexExtendedPipeline.java:70)
	at org.gbif.pipelines.ingest.pipelines.InterpretedToEsIndexExtendedPipeline.main(InterpretedToEsIndexExtendedPipeline.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:688)
```

`sudo -u hdfs spark2-submit --conf spark.metrics.conf=/home/crap/config/metrics.properties --conf "spark.driver.extraClassPath=/home/crap/lib/logstash-gelf.jar" --driver-java-options "-Dlog4j.configuration=file:/home/crap/config/log4j-indexing-pipeline.properties" --queue root.pipelines --conf spark.default.parallelism=200 --conf spark.executor.memoryOverhead=4096 --conf spark.dynamicAllocation.enabled=false --conf "spark.executor.extraJavaOptions=-XX:+UseG1GC" --class org.gbif.pipelines.ingest.pipelines.InterpretedToEsIndexExtendedPipeline --master yarn --deploy-mode cluster --executor-memory 10G --executor-cores 5 --num-executors 10 --driver-memory 1G hdfs://ha-nn/pipelines/jars/ingest-gbif.jar --datasetId=f2e389da-39c3-4f21-8d72-b7d574d924a9 --attempt=90 --runner=SparkRunner --inputPath=hdfs://ha-nn/data/ingest --targetPath=hdfs://ha-nn/data/ingest --metaFileName=interpreted-to-index.yml --hdfsSiteConfig=/home/crap/config/hdfs-site.xml --coreSiteConfig=/home/crap/config/core-site.xml --esHosts=http://c6n1.gbif.org:9200,http://c6n2.gbif.org:9200,http://c6n3.gbif.org:9200,http://c6n4.gbif.org:9200,http://c6n5.gbif.org:9200,http://c6n6.gbif.org:9200,http://c6n7.gbif.org:9200,http://c6n8.gbif.org:9200,http://c6n9.gbif.org:9200,http://c6n10.gbif.org:9200,http://c6n11.gbif.org:9200,http://c6n12.gbif.org:9200,http://c6n1.gbif.org:9201,http://c6n2.gbif.org:9201,http://c6n3.gbif.org:9201,http://c6n4.gbif.org:9201,http://c6n5.gbif.org:9201,http://c6n6.gbif.org:9201,http://c6n7.gbif.org:9201,http://c6n8.gbif.org:9201,http://c6n9.gbif.org:9201,http://c6n10.gbif.org:9201,http://c6n11.gbif.org:9201,http://c6n12.gbif.org:9201,http://c6n1.gbif.org:9202,http://c6n2.gbif.org:9202,http://c6n3.gbif.org:9202,http://c6n4.gbif.org:9202,http://c6n5.gbif.org:9202,http://c6n6.gbif.org:9202,http://c6n7.gbif.org:9202,http://c6n8.gbif.org:9202,http://c6n9.gbif.org:9202,http://c6n10.gbif.org:9202,http://c6n11.gbif.org:9202,http://c6n12.gbif.org:9202,http://c6n1.gbif.org:9203,http://c6n2.gbif.org:9203,http://c6n3.gbif.org:9203,http://c6n4.gbif.org:9203,http://c6n5.gbif.org:9203,http://c6n6.gbif.org:9203,http://c6n7.gbif.org:9203,http://c6n8.gbif.org:9203,http://c6n9.gbif.org:9203,http://c6n10.gbif.org:9203,http://c6n11.gbif.org:9203,http://c6n12.gbif.org:9203 --properties=/home/crap/config/pipelines.properties --esIndexName=f2e389da-39c3-4f21-8d72-b7d574d924a9_90_1565678998932 --esAlias=f2e389da-39c3-4f21-8d72-b7d574d924a9,occurrence --indexNumberShards=2`

**Comment by muttcg** [comment]
One more 
```
962f59bc-f762-11e1-a439-00145eb45e9a 110 19/08/13 07:43:48 ERROR ApplicationMaster: User class threw exception: com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
 at [Source: UNKNOWN; line: 1, column: 1]
com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
 at [Source: UNKNOWN; line: 1, column: 1]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
	at com.fasterxml.jackson.databind.ObjectReader._initForReading(ObjectReader.java:381)
	at com.fasterxml.jackson.databind.ObjectReader._bindAsTree(ObjectReader.java:1539)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndCloseAsTree(ObjectReader.java:1528)
	at com.fasterxml.jackson.databind.ObjectReader.readTree(ObjectReader.java:1235)
	at org.gbif.pipelines.estools.service.JsonHandler.readTree(JsonHandler.java:86)
	at org.gbif.pipelines.estools.service.HttpRequestBuilder.withMappings(HttpRequestBuilder.java:95)
	at org.gbif.pipelines.estools.service.HttpRequestBuilder.createBodyFromIndexParams(HttpRequestBuilder.java:53)
	at org.gbif.pipelines.estools.service.EsService.createIndex(EsService.java:54)
	at org.gbif.pipelines.ingest.utils.EsIndexUtils.createIndexAndAliasForDefault(EsIndexUtils.java:54)
	at org.gbif.pipelines.ingest.pipelines.InterpretedToEsIndexExtendedPipeline.run(InterpretedToEsIndexExtendedPipeline.java:77)
	at org.gbif.pipelines.ingest.pipelines.InterpretedToEsIndexExtendedPipeline.run(InterpretedToEsIndexExtendedPipeline.java:70)
	at org.gbif.pipelines.ingest.pipelines.InterpretedToEsIndexExtendedPipeline.main(InterpretedToEsIndexExtendedPipeline.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:688)
```

`sudo -u hdfs spark2-submit --conf spark.metrics.conf=/home/crap/config/metrics.properties --conf "spark.driver.extraClassPath=/home/crap/lib/logstash-gelf.jar" --driver-java-options "-Dlog4j.configuration=file:/home/crap/config/log4j-indexing-pipeline.properties" --queue root.pipelines --conf spark.default.parallelism=60 --conf spark.executor.memoryOverhead=4096 --conf spark.dynamicAllocation.enabled=false --conf "spark.executor.extraJavaOptions=-XX:+UseG1GC" --class org.gbif.pipelines.ingest.pipelines.InterpretedToEsIndexExtendedPipeline --master yarn --deploy-mode cluster --executor-memory 8G --executor-cores 5 --num-executors 3 --driver-memory 1G hdfs://ha-nn/pipelines/jars/ingest-gbif.jar --datasetId=962f59bc-f762-11e1-a439-00145eb45e9a --attempt=110 --runner=SparkRunner --inputPath=hdfs://ha-nn/data/ingest --targetPath=hdfs://ha-nn/data/ingest --metaFileName=interpreted-to-index.yml --hdfsSiteConfig=/home/crap/config/hdfs-site.xml --coreSiteConfig=/home/crap/config/core-site.xml --esHosts=http://c6n1.gbif.org:9200,http://c6n2.gbif.org:9200,http://c6n3.gbif.org:9200,http://c6n4.gbif.org:9200,http://c6n5.gbif.org:9200,http://c6n6.gbif.org:9200,http://c6n7.gbif.org:9200,http://c6n8.gbif.org:9200,http://c6n9.gbif.org:9200,http://c6n10.gbif.org:9200,http://c6n11.gbif.org:9200,http://c6n12.gbif.org:9200,http://c6n1.gbif.org:9201,http://c6n2.gbif.org:9201,http://c6n3.gbif.org:9201,http://c6n4.gbif.org:9201,http://c6n5.gbif.org:9201,http://c6n6.gbif.org:9201,http://c6n7.gbif.org:9201,http://c6n8.gbif.org:9201,http://c6n9.gbif.org:9201,http://c6n10.gbif.org:9201,http://c6n11.gbif.org:9201,http://c6n12.gbif.org:9201,http://c6n1.gbif.org:9202,http://c6n2.gbif.org:9202,http://c6n3.gbif.org:9202,http://c6n4.gbif.org:9202,http://c6n5.gbif.org:9202,http://c6n6.gbif.org:9202,http://c6n7.gbif.org:9202,http://c6n8.gbif.org:9202,http://c6n9.gbif.org:9202,http://c6n10.gbif.org:9202,http://c6n11.gbif.org:9202,http://c6n12.gbif.org:9202,http://c6n1.gbif.org:9203,http://c6n2.gbif.org:9203,http://c6n3.gbif.org:9203,http://c6n4.gbif.org:9203,http://c6n5.gbif.org:9203,http://c6n6.gbif.org:9203,http://c6n7.gbif.org:9203,http://c6n8.gbif.org:9203,http://c6n9.gbif.org:9203,http://c6n10.gbif.org:9203,http://c6n11.gbif.org:9203,http://c6n12.gbif.org:9203 --properties=/home/crap/config/pipelines.properties --esIndexName=962f59bc-f762-11e1-a439-00145eb45e9a_110 --esAlias=962f59bc-f762-11e1-a439-00145eb45e9a,occurrence --indexNumberShards=1`
