### ISSUE TITLE
ES can't insert the document

### ISSUE THREAD

**Issue by muttcg** [gbif/pipelines#241]
https://registry.gbif.org/dataset/13b70480-bd69-11dd-b15f-b8a03c50a862/history

Document id 865115754: failed to parse (mapper_parsing_exception)
```
Caused by: failed to parse [null]: expected text or object, but got VALUE_NUMBER (parsing_exception)
	at org.apache.beam.sdk.io.elasticsearch.ElasticsearchIO.checkForErrors(ElasticsearchIO.java:221)
	at org.apache.beam.sdk.io.elasticsearch.ElasticsearchIO$Write$WriteFn.flushBatch(ElasticsearchIO.java:1297)
	at org.apache.beam.sdk.io.elasticsearch.ElasticsearchIO$Write$WriteFn.processElement(ElasticsearchIO.java:1259)
```

**Comment by muttcg** [comment]
looks like we have some es schema difference,  got the issue for the index **default-dynamic_201911131446_1573668498422** , but index **default-dynamic_1574279665360** works well

**Comment by muttcg** [comment]
Fixed in https://github.com/gbif/pipelines/commit/6446080e7de421ee3711d32fe818f516ad39c66d
