### ISSUE TITLE
Suggestion: Convert RecordType enum to interface

### ISSUE THREAD

**Issue by djtfmartin** [gbif/pipelines#248]
To help with extensibility, suggest `RecordType` enum is converted to an interface and a separate enum is created that implements this interface that includes the current list of transform types in use by GBIF. 

https://github.com/gbif/pipelines/blob/master/pipelines/common/src/main/java/org/gbif/pipelines/common/PipelinesVariables.java#L35

**Comment by djtfmartin** [comment]
Just a follow up to this, we discussed as a workaround just passing a null value for RecordType in the constructors for Transforms which call super class like so
```
  private ALATaxonomyTransform(KeyValueStore<SpeciesMatchRequest, NameUsageMatch> kvStore, KvConfig kvConfig) {
    super(ALATaxonRecord.class, null, ALATaxonomyTransform.class.getName(), "alaTaxonRecordsCount");
    this.kvStore = kvStore;
    this.kvConfig = kvConfig;
  }
```

This causes the following NPE

```
Exception in thread "main" java.lang.NullPointerException
	at org.gbif.pipelines.transforms.Transform.<init>(Transform.java:47)
	at au.org.ala.pipelines.transforms.ALATaxonomyTransform.<init>(ALATaxonomyTransform.java:43)
	at au.org.ala.pipelines.transforms.ALATaxonomyTransform.create(ALATaxonomyTransform.java:65)
	at au.org.ala.pipelines.java.ALAVerbatimToInterpretedPipeline.run(ALAVerbatimToInterpretedPipeline.java:149)
	at au.org.ala.pipelines.java.ALAVerbatimToInterpretedPipeline.run(ALAVerbatimToInterpretedPipeline.java:102)
	at au.org.ala.pipelines.java.ALAVerbatimToInterpretedPipeline.run(ALAVerbatimToInterpretedPipeline.java:96)
	at au.org.ala.pipelines.java.ALAVerbatimToInterpretedPipeline.main(ALAVerbatimToInterpretedPipeline.java:91)
```

**Comment by muttcg** [comment]
In the master branch
