### ISSUE TITLE
Index deletion fails cause of timeout

### ISSUE THREAD

**Issue by muttcg** [gbif/pipelines#269]
Because index deletion can take some time, we have a timeout in the code ~10min, but if it takes too long spark throws:
`20/05/21 03:04:45 ERROR ApplicationMaster: Uncaught exception: 
java.util.concurrent.TimeoutException: Futures timed out after [100000 milliseconds]
	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:201)
	at org.apache.spark.deploy.yarn.ApplicationMaster.runDriver(ApplicationMaster.scala:455)
	at org.apache.spark.deploy.yarn.ApplicationMaster.org$apache$spark$deploy$yarn$ApplicationMaster$$runImpl(ApplicationMaster.scala:301)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anonfun$run$1.apply$mcV$sp(ApplicationMaster.scala:241)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anonfun$run$1.apply(ApplicationMaster.scala:241)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anonfun$run$1.apply(ApplicationMaster.scala:241)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$3.run(ApplicationMaster.scala:782)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1924)
	at org.apache.spark.deploy.yarn.ApplicationMaster.doAsUser(ApplicationMaster.scala:781)
	at org.apache.spark.deploy.yarn.ApplicationMaster.run(ApplicationMaster.scala:240)
	at org.apache.spark.deploy.yarn.ApplicationMaster$.main(ApplicationMaster.scala:806)
	at org.apache.spark.deploy.yarn.ApplicationMaster.main(ApplicationMaster.scala)`

Looks Spark/YARN setting must be added to extend timeout:

[Some setting similar to this](https://issues.apache.org/jira/browse/SPARK-16870)

**Comment by timrobertson100** [comment]
`yarn.resourcemanager.container.liveness-monitor.interval-ms` which is the YARN way to monitor containers is set to 10 minutes.

The `spark.yarn.am.waitTime` defaults to 100s which matches the error, but it implies the spark context itself isn't initialized. Given that the timeout matches, and I can't see anything else defaulting to 100s, I'd suggest we at least start with adding `--conf spark.yarn.am.waitTime=360s` but I am not confident in that.

**Comment by muttcg** [comment]
Haven't seen after the fix, I will reopen in case it appears again
