### ISSUE TITLE
Interpretation fails when trying to call org.gbif.pipelines.core.ws.metadata.response.Dataset

### ISSUE THREAD

**Issue by muttcg** [gbif/pipelines#384]
Caused by: javax.xml.ws.WebServiceException: Error getting content data for dataset org.gbif.pipelines.core.ws.metadata.response.Dataset@510c2650
	at org.gbif.pipelines.core.ws.metadata.MetadataServiceClient.lambda$getContentProjectData$1(MetadataServiceClient.java:112)
	at io.github.resilience4j.retry.Retry.lambda$decorateFunction$7(Retry.java:313)
	at org.gbif.pipelines.core.ws.metadata.MetadataServiceClient.getContentProjectData(MetadataServiceClient.java:116)
	at org.gbif.pipelines.core.ws.metadata.MetadataServiceClient.getDataset(MetadataServiceClient.java:96)
	at org.gbif.pipelines.transforms.metadata.DefaultValuesTransform.setup(DefaultValuesTransform.java:61)
Caused by: java.lang.IllegalStateException: Request cannot be executed; I/O reactor status: STOPPED
	at hc45.org.apache.http.util.Asserts.check(Asserts.java:46)
	at hc45.org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase.ensureRunning(CloseableHttpAsyncClientBase.java:90)
	at hc45.org.apache.http.impl.nio.client.InternalHttpAsyncClient.execute(InternalHttpAsyncClient.java:123)
	at org.elasticsearch.client.RestClient.performRequestAsync(RestClient.java:531)
	at org.elasticsearch.client.RestClient.performRequestAsyncNoCatch(RestClient.java:516)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:228)
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1593)
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1563)
	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1525)
	at org.elasticsearch.client.RestHighLevelClient.search(RestHighLevelClient.java:990)
	at org.gbif.pipelines.core.ws.metadata.contentful.ContentService.getProject(ContentService.java:69)
	at org.gbif.pipelines.core.ws.metadata.MetadataServiceClient.lambda$getContentProjectData$1(MetadataServiceClient.java:110)

**Comment by muttcg** [comment]
in prod
