### ISSUE TITLE
NPE in LocationInterpreter.interpretMinimumElevationInMeters - MeterRangeParser

### ISSUE THREAD

**Issue by djtfmartin** [gbif/pipelines#434]
```
Exception in thread "main" org.apache.beam.sdk.Pipeline$PipelineExecutionException: java.lang.NullPointerException
	at org.apache.beam.runners.spark.SparkPipelineResult.beamExceptionFrom(SparkPipelineResult.java:69)
	at org.apache.beam.runners.spark.SparkPipelineResult.waitUntilFinish(SparkPipelineResult.java:102)
	at org.apache.beam.runners.spark.SparkPipelineResult.waitUntilFinish(SparkPipelineResult.java:90)
	at au.org.ala.pipelines.beam.ALAVerbatimToInterpretedPipeline.run(ALAVerbatimToInterpretedPipeline.java:284)
	at au.org.ala.pipelines.beam.ALAVerbatimToInterpretedPipeline.main(ALAVerbatimToInterpretedPipeline.java:102)
Caused by: java.lang.NullPointerException
	at org.gbif.common.parsers.geospatial.MeterRangeParser.parseInMeter(MeterRangeParser.java:382)
	at org.gbif.common.parsers.geospatial.MeterRangeParser.parseMeters(MeterRangeParser.java:338)
	at org.gbif.pipelines.core.interpreters.core.LocationInterpreter.interpretMinimumElevationInMeters(LocationInterpreter.java:183)
	at org.gbif.pipelines.core.interpreters.Interpretation$Handler.lambda$via$0(Interpretation.java:95)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.gbif.pipelines.core.interpreters.Interpretation$Handler.via(Interpretation.java:95)
	at au.org.ala.pipelines.transforms.LocationTransform.processElement(LocationTransform.java:160)
	at au.org.ala.pipelines.transforms.LocationTransform.processElement(LocationTransform.java:141)
```

Working to identify the record that causes this. The dataset is the ALA dataset dr344.

**Comment by timrobertson100** [comment]
Looks like unboxing issue in the parsers project. I'll add a test and fix

**Comment by timrobertson100** [comment]
Can you please pull and confirm the NPE is now gone @djtfmartin ?

Example of content which could cause this: `Somewhere between (1-2m) or (3-6ft)`

**Comment by djtfmartin** [comment]
thanks @timrobertson100  - i've tested with the dataset that highlighted the issue and confirmed this fixed the NPE.
