### ISSUE TITLE
Corrupt DWCA ingestion gets stuck

### ISSUE THREAD

**Issue by MattBlissett** [gbif/pipelines#539]
A corrupt DWCA having `<field index="6" term=""/>` causes this exception:

```
java.lang.NullPointerException: null
	at org.gbif.pipelines.core.converters.ExtendedRecordConverter.convertToMap(ExtendedRecordConverter.java:26)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at org.gbif.pipelines.core.converters.ExtendedRecordConverter.lambda$from$2(ExtendedRecordConverter.java:50)
	at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1321)
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1699)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at org.gbif.pipelines.core.converters.ExtendedRecordConverter.from(ExtendedRecordConverter.java:44)
	at org.gbif.pipelines.core.io.DwcaReader.lambda$new$1(DwcaReader.java:53)
	at org.gbif.pipelines.core.io.DwcaReader.advance(DwcaReader.java:73)
	at org.gbif.converters.DwcaToAvroConverter.convert(DwcaToAvroConverter.java:44)
	at org.gbif.converters.converter.ConverterToVerbatim.convert(ConverterToVerbatim.java:105)
	at org.gbif.pipelines.crawler.dwca.DwcaToAvroCallback.lambda$createRunnable$0(DwcaToAvroCallback.java:107)
	at org.gbif.pipelines.crawler.PipelinesCallback.handleMessage(PipelinesCallback.java:157)
	at org.gbif.pipelines.crawler.dwca.DwcaToAvroCallback.handleMessage(DwcaToAvroCallback.java:63)
	at org.gbif.pipelines.crawler.dwca.DwcaToAvroCallback.handleMessage(DwcaToAvroCallback.java:32)
	at org.gbif.common.messaging.MessageConsumer.handleCallback(MessageConsumer.java:121)
	at org.gbif.common.messaging.MessageConsumer.handleDelivery(MessageConsumer.java:84)
	at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:149)
	at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:104)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

The ingestion is never ended — the processOccurrenceState in ZK remains 'Running', so the entry is not cleaned up and the next crawl is blocked.

**Comment by muttcg** [comment]
What would be the best, skip null terms or fail the step?

**Comment by MattBlissett** [comment]
The archive doesn't validate, so I think just fail the step.

**Comment by muttcg** [comment]
Deployed to PROD
