### ISSUE TITLE
Unrecognized field "tags" (class org.gbif.vocabulary.model.Concept)

### ISSUE THREAD

**Issue by djtfmartin** [gbif/pipelines#572]
We've found this problem when running `ALAVerbatimToInterpretedPipeline` - we suspect because of changes to vocabulary services.

```
Caused by: vocab.com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "tags" (class org.gbif.vocabulary.model.Concept), not marked as ignorable (19 known properties: "modifiedBy", "created", "modified", "deprecatedBy", "name", "alternativeLabels", "definition", "label", "externalDefinitions", "replacedByKey", "deleted", "editorialNotes", "key", "hiddenLabels", "deprecated", "parentKey", "vocabularyKey", "createdBy", "sameAsUris"])
 at [Source: UNKNOWN; line: 1, column: 1327] (through reference chain: org.gbif.vocabulary.model.export.VocabularyExport["concepts"]->java.util.ArrayList[0]->org.gbif.vocabulary.model.Concept["tags"])
	at vocab.com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
	at vocab.com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:843)
	at vocab.com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1206)
	at vocab.com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1592)
	at vocab.com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1570)
	at vocab.com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:294)
	at vocab.com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at vocab.com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286)
	at vocab.com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
	at vocab.com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
	at vocab.com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at vocab.com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at vocab.com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at vocab.com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4218)
	at vocab.com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3251)
	at org.gbif.vocabulary.lookup.VocabularyLookup.importVocabulary(VocabularyLookup.java:265)
	at org.gbif.vocabulary.lookup.VocabularyLookup.<init>(VocabularyLookup.java:131)
	at org.gbif.vocabulary.lookup.VocabularyLookup.<init>(VocabularyLookup.java:92)
	at org.gbif.vocabulary.lookup.VocabularyLookup$VocabularyLookupBuilder.build(VocabularyLookup.java:406)
	at org.gbif.pipelines.core.factory.FileVocabularyFactory.lambda$getInstanceSupplier$9a675d58$1(FileVocabularyFactory.java:62)
	at au.org.ala.pipelines.transforms.ALABasicTransform.setup(ALABasicTransform.java:82)
```

**Comment by timrobertson100** [comment]
ALA are running again using the previous JSON file.

This was discovered by ALA as they have a daily cron, while GBIF don't. Suggest we review how GBIF brings vocabularies into pipelines as we should have found this too.

It might make sense to add a "ignoreUnknownFields" in the client parsing the JSON. Our v1 API policy for the last 8 years has been to not deploy breaking changes, but adding fields was acceptable which is what happened here.

**Comment by marcos-lg** [comment]
I fixed the vocabulary-lookup library to ignore unknown properties and updated pipelines to use this new version: https://github.com/gbif/pipelines/commit/94b2681f3ac758de745e2f0cdf7a024885728508

In GBIF pipelines it didn't fail because we only update the json file when a vocabulary is released (we have a cli that does this automatically). Also the view returned in https://api.gbif.org/v1/vocabularies/LifeStage/releases/1.0.3/export is not consistent with the actual released version (I'll fix this too).

**Comment by timrobertson100** [comment]
Thanks @marcos-lg 

Can you please ensure that http://api.gbif.org/v1/vocabularies/LifeStage/releases/latest/export is returning the latest *released* version too, please? That is what ALA calls on the daily cron.

**Comment by marcos-lg** [comment]
> Also the view returned in https://api.gbif.org/v1/vocabularies/LifeStage/releases/1.0.3/export is not consistent with the actual released version (I'll fix this too).

Just deployed the fix for this

**Comment by djtfmartin** [comment]
thanks @marcos-lg
