### ISSUE TITLE
InterpretedToEsIndexPipeline fails cause of "can't create native thread issue"

### ISSUE THREAD

**Issue by muttcg** [gbif/pipelines#644]
Current DEV version (2.10.0-SNAPSHOT) has some resources releasing issues, some IO resources don't close and after time application fails because of "can't create native thread issue".

Threads are constantly growing:
```
$ ps -T -p 15506 | wc -l
14549
$ ps -T -p 15506 | wc -l
15233
$ ps -T -p 15506 | wc -l
15755
```

and after hitting the OS limit:
```
Caused by: java.lang.RuntimeException: Request cannot be executed; I/O reactor status: STOPPED
	at org.elasticsearch.client.RestClient.extractAndWrapCause(RestClient.java:857)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:259)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:262)
```

**Comment by muttcg** [comment]
So there is no difference in code between master and dev, but dev version creates some `I/O dispatcher` (presume opened by _apache http async client_ from _ES client_) threads and doesn't close them after, possible some changes in the libraries (pom) caused this by including different apache/es clients/etc verions
