### ISSUE TITLE
Some ALA tests fail spontaneously 

### ISSUE THREAD

**Issue by muttcg** [gbif/pipelines#872]
Some builds fail randomly, more often happens during releasing artifices:

```
12:21:43,634 [INFO] 12:21:43,633 [ERROR] au.org.ala.pipelines.java.CompleteIngestJavaPipelineTestIT.testIngestPipeline  Time elapsed: 4.904 s  <<< ERROR!
12:21:43,634 [INFO] org.apache.beam.sdk.Pipeline$PipelineExecutionException: java.lang.RuntimeException: Unrecognised field name: georeferencedDate
12:21:43,634 [INFO] 	at org.apache.beam.runners.direct.DirectRunner$DirectPipelineResult.waitUntilFinish(DirectRunner.java:373)
12:21:43,634 [INFO] 	at org.apache.beam.runners.direct.DirectRunner$DirectPipelineResult.waitUntilFinish(DirectRunner.java:341)
12:21:43,634 [INFO] 	at org.apache.beam.runners.direct.DirectRunner.run(DirectRunner.java:218)
12:21:43,634 [INFO] 	at org.apache.beam.runners.direct.DirectRunner.run(DirectRunner.java:67)
12:21:43,635 [INFO] 	at org.apache.beam.sdk.Pipeline.run(Pipeline.java:323)
12:21:43,635 [INFO] 	at org.apache.beam.sdk.Pipeline.run(Pipeline.java:309)
12:21:43,635 [INFO] 	at au.org.ala.pipelines.beam.ALAInterpretedToSensitivePipeline.run(ALAInterpretedToSensitivePipeline.java:142)
12:21:43,635 [INFO] 	at au.org.ala.pipelines.java.CompleteIngestJavaPipelineTestIT.loadTestDataset(CompleteIngestJavaPipelineTestIT.java:150)
12:21:43,635 [INFO] 	at au.org.ala.pipelines.java.CompleteIngestJavaPipelineTestIT.testIngestPipeline(CompleteIngestJavaPipelineTestIT.java:48)
12:21:43,635 [INFO] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
12:21:43,637 [INFO] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
12:21:43,637 [INFO] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
12:21:43,637 [INFO] 	at java.lang.reflect.Method.invoke(Method.java:498)
12:21:43,637 [INFO] 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
12:21:43,637 [INFO] 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
12:21:43,637 [INFO] 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
12:21:43,637 [INFO] 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
12:21:43,637 [INFO] 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
12:21:43,638 [INFO] 	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
12:21:43,638 [INFO] 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
12:21:43,638 [INFO] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
12:21:43,638 [INFO] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
12:21:43,638 [INFO] 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
12:21:43,638 [INFO] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
12:21:43,638 [INFO] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
12:21:43,638 [INFO] 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
12:21:43,638 [INFO] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
12:21:43,640 [INFO] 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
12:21:43,640 [INFO] 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
12:21:43,640 [INFO] 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
12:21:43,640 [INFO] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
12:21:43,640 [INFO] 	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:364)
12:21:43,640 [INFO] 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:272)
12:21:43,640 [INFO] 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:237)
12:21:43,642 [INFO] 	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:158)
12:21:43,642 [INFO] 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
12:21:43,642 [INFO] 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
12:21:43,642 [INFO] 	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
12:21:43,642 [INFO] 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
12:21:43,642 [INFO] Caused by: java.lang.RuntimeException: Unrecognised field name: georeferencedDate
12:21:43,642 [INFO] 	at au.org.ala.pipelines.interpreters.SensitiveDataInterpreter.constructFields(SensitiveDataInterpreter.java:156)
12:21:43,642 [INFO] 	at au.org.ala.pipelines.transforms.ALASensitiveDataRecordTransform.convert(ALASensitiveDataRecordTransform.java:214)
12:21:43,642 [INFO] 	at au.org.ala.pipelines.transforms.ALASensitiveDataRecordTransform.convert(ALASensitiveDataRecordTransform.java:46)
12:21:43,642 [INFO] 	at org.gbif.pipelines.transforms.Transform.processElement(Transform.java:157)
12:21:43,642 [INFO] 	at org.gbif.pipelines.transforms.Transform.processElement(Transform.java:153)
12:21:43,642 [INFO] 
```

**Comment by muttcg** [comment]
```
12:50:04,275 [INFO] Caused by: java.lang.RuntimeException: Unrecognised field name: waterBody
12:50:04,275 [INFO] 	at au.org.ala.pipelines.interpreters.SensitiveDataInterpreter.constructFields(SensitiveDataInterpreter.java:156)
12:50:04,275 [INFO] 	at 
```
