### ISSUE TITLE
EVENTS_VERBATIM_TO_INTERPRETED step interpretation fails due to an obscure issue

### ISSUE THREAD

**Issue by muttcg** [gbif/pipelines#899]
https://registry.gbif.org/dataset/22c0b11e-f891-442a-8273-9283c986ddc7

```
23/05/16 08:35:33 ERROR ApplicationMaster: User class threw exception: java.lang.RuntimeException: java.lang.InterruptedException
java.lang.RuntimeException: java.lang.InterruptedException
	at org.apache.beam.runners.spark.SparkPipelineResult.runtimeExceptionFrom(SparkPipelineResult.java:60)
	at org.apache.beam.runners.spark.SparkPipelineResult.beamExceptionFrom(SparkPipelineResult.java:77)
	at org.apache.beam.runners.spark.SparkPipelineResult.waitUntilFinish(SparkPipelineResult.java:107)
	at org.apache.beam.runners.spark.SparkPipelineResult.waitUntilFinish(SparkPipelineResult.java:92)
	at org.gbif.pipelines.ingest.pipelines.VerbatimToEventPipeline.run(VerbatimToEventPipeline.java:217)
	at org.gbif.pipelines.ingest.pipelines.VerbatimToEventPipeline.run(VerbatimToEventPipeline.java:87)
	at org.gbif.pipelines.ingest.pipelines.VerbatimToEventPipeline.main(VerbatimToEventPipeline.java:83)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:688)
Caused by: java.lang.InterruptedException
	at java.util.concurrent.FutureTask.awaitDone(FutureTask.java:404)
	at java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at org.apache.beam.runners.spark.SparkPipelineResult$BatchMode.awaitTermination(SparkPipelineResult.java:145)
	at org.apache.beam.runner
```

**Comment by muttcg** [comment]
List of datasets where the issue occurred:
https://registry.gbif.org/dataset/9e6691f5-cb9d-4387-8e56-5b5529cfb35e
https://registry.gbif.org/dataset/ad33d5cc-613d-4bd3-b33e-c2dd16e75248
https://registry.gbif.org/dataset/60390d19-0ed3-481e-aaf7-4eb1956c6a24
https://registry.gbif.org/dataset/efadcbcc-c772-489d-9544-a571371a0687
https://registry.gbif.org/dataset/6cef8c28-b4dd-4082-af20-57cdc660a5bd
https://registry.gbif.org/dataset/9b6cdc0f-70f6-4d08-8cbb-444dd0001a19
https://registry.gbif.org/dataset/af105838-8385-4fff-ab5b-04eb5b9fee39
https://registry.gbif.org/dataset/9f6c8cc3-b7c0-4bd5-a3bf-9fb221f73c2c
https://registry.gbif.org/dataset/13608638-5c18-4b1d-aa45-6d6c8f1f49d2
https://registry.gbif.org/dataset/385f5b18-5ceb-4458-ab4b-84d7850034fd

**Comment by muttcg** [comment]
It seems likely caused by data records where users use the same ID for eventID and parentEventID, creating recursive calls. Example:
```
    "http://rs.tdwg.org/dwc/terms/eventID": "br:sibbr:peld:rlac:comunidadepeixes20080225:1",
     ...
    "http://rs.tdwg.org/dwc/terms/parentEventID": "br:sibbr:peld:rlac:comunidadepeixes20080225:1",
```

**Comment by muttcg** [comment]
Fixed
